version: "3"
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=12345678'
      - 'POSTGRES_USER=postgres'

    ports:
      - "5432:5432"

  appservice:
    build: ./
    depends_on:
      - postgres
    environment:
    - spring.datasource.url=jdbc:postgresql://postgres:5432/postgres?createDatabaseIfNotExist=true
    - spring.datasource.driver-class-name=org.postgresql.Driver
    - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    - spring.datasource.username=postgres
    - spring.datasource.password=12345678
    ports:
      - "8085:8085"

